[project]
name = "xsd"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Daxexs", email = "Daxexsdev@gmail.com"},
]
dependencies = [
    "flet",
    "fastapi",
    "sqlmodel"
]
requires-python = ">=3.8"
readme = "README.md"
license = {text = "MIT"}